### ISSUE TITLE
Possible problem with tests running in a setgid dir

### ISSUE THREAD

**Issue by OnkelTem** [gulpjs/vinyl-fs#103]
These tests fail on my system (Linux/Ubuntu):

1) dest stream should write directories to the right folder
2) dest stream should use different modes for files and directories
3) symlink stream should use different modes for files and directories

After some debugging I figured out that all three tests fail due to the project directory (and its subdirectories) permissions which has `setgid` bit set.

To reproduce execute this command:
```
$ find test -type d -exec chmod g+s {} \;
```
and then run the tests.

=
**Whys**

Let's look at the first failing test `should write directories to the right folder`.
The expected mode of a dir is:
```js
var expectedMode = parseInt('655', 8);
```
and the failing line is:
```js
realMode(fs.lstatSync(expectedPath).mode).should.equal(expectedMode);
```
and my run-time values were:
```js
fs.lstatSync(expectedPath).mode.toString(8) // 42655
realMode(fs.lstatSync(expectedPath).mode).toString(8) // 2655 != 655 (expectedMode)
```
— i.e. it didn't expect an extra bit set by the filesystem.

Ideas? Can't we just make `realMode()` more loosing like this:
```patch
var realMode = function(n) {
-  return n & parseInt('7777', 8);
+  return n & parseInt('777', 8);
};
```

**Comment by contra** [comment]
PR?
