### ISSUE TITLE
Lint the tests/ directory?

### ISSUE THREAD

**Issue by pdehaan** [gulpjs/vinyl-fs#117]
Per [package.json:40](https://github.com/gulpjs/vinyl-fs/blob/a28ba42d87eeaecc2ae3de9174270019fab76fe3/package.json#L40),

Currently only linting the lib/** folder.
Probably after we merge https://github.com/gulpjs/vinyl-fs/pull/115 since we'd want to update the JSCS paths as well.

**Comment by phated** [comment]
Resolved by #115
