### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by piranna** [gulpjs/vinyl-fs#118]
(Maybe related to issue #113 and it's solution at version 2.2.1)

I'm getting errors when extracting the content from http://downloads.sourceforge.net/fuse/fuse-2.9.4.tar.gz using [download](https://github.com/kevva/download). By adding a `console.log(writePath, stat)` to the `utimes` function I've found that `atime` is defined as a "Invalid Date", and since it's *already defined* [it's not being assigned a new Date object](https://github.com/gulpjs/vinyl-fs/blob/a28ba42d87eeaecc2ae3de9174270019fab76fe3/lib/utimes.js#L12), so [the subsequent check fails](https://github.com/gulpjs/vinyl-fs/blob/a28ba42d87eeaecc2ae3de9174270019fab76fe3/lib/utimes.js#L14):

```Javascript
{ dev: undefined,
  mode: 420,
  nlink: undefined,
  uid: 1000,
  gid: 100,
  rdev: undefined,
  blksize: undefined,
  ino: undefined,
  size: 10858,
  blocks: undefined,
  atime: Invalid Date,
  mtime: Mon Feb 18 2013 10:41:39 GMT+0100 (CET),
  ctime: Invalid Date,
  birthtime: Invalid Date,
  name: 'fuse-2.9.4/README',
  type: 'file',
  linkname: null,
  uname: '',
  gname: '',
  devmajor: 0,
  devminor: 0 }
```

I think `stat.atime` should be check previously to know if it's a valid one and if not assign a new one.

**Comment by piranna** [comment]
I've create a [pull-request](https://github.com/gulpjs/vinyl-fs/pull/119) to fix this.

**Comment by phated** [comment]
Merged.  Will be published with another bug fix
