### ISSUE TITLE
vfs-dest doesnt end?

### ISSUE THREAD

**Issue by davidchase** [gulpjs/vinyl-fs#120]
Maybe i missing something so i apologize in advanced... i know `vfs.dest` returns a readable/writable stream... so is up to the user to end that stream?

for example if i simply do `vfs.src.pipe(vsf.dest)` and the source contains 17+ files the destination folder will only have 16 files since thats the limit of the highWaterMark, 

however if i pipe from `dest` like so `vfs.src.pipe(vsf.dest).pipe(...)` or attach a `data` listener then i will get all of the files from the source to destination since i drain and keep the flow going...

so that additional pipe or adding a `data` listener to simply copy files in my basic example feels a bit odd but i can understand if thats the intent to have the user of `vinyl-fs` to choose what happens with the stream.

thanks
-david

**Comment by phated** [comment]
dest should be pulling files from the stream. It always has, the only time you should have to drain is if you don't have a dest or some other stream pulling on the end of the pipeline

**Comment by davidchase** [comment]
@phated thanks for the quick reply but i guess im not exactly following..

lets say i have 17 files inside `client/src/js` and i want to move them to `client/dest/js` for sake of simplicity i have no transforms its essentially a "copy/paste":

if i do `vfs.src('./client/src/*.js').pipe(vfs.dest('client/dest/js'))` only 16 of those 17 files would move from the source directory to the destination directory.

unless i add some `pipe` after the `dest`, is that a correct intuition ?

**Comment by phated** [comment]
No, the dest method was written in a way that empties the stream so you won't pause at 16 files

**Comment by davidchase** [comment]
but only 16 out of 17 files transfer to the `dest` folder something is not working...

with the gulp and older `vinyl-fs` which is `0.3.0` it transfers all files with gulp and a newer `vinyl-fs` at `2.2.0` it does **not** transfer all of the files

according to this commit https://github.com/gulpjs/vinyl-fs/commit/99db7de8f0485c5ca158c79126b53b8fdab9d821#diff-ebdf4495a061217916345559e7783922L19 

it used to do `stream.resume()`

**Comment by phated** [comment]
@davidchase thanks for tracking that down.  That's what I was trying to understand.  Sorry for being confusing, every response was from my phone.  This is something we need to fix.

**Comment by davidchase** [comment]
:+1: yeah i just found out that with your guys new `gulp v4` which uses `vinyl-fs@2.2.0` this issue is circumvented by using `stream-exhaust`  which handles a resume or pipes to a sink... so i decided to use `stream-exhaust` myself for the time being :smile:

**Comment by Klowner** [comment]
It seems like if you return the stream from your `gulp.task` function then it properly drains, but that prevents use of the task completion callback style ("called too many times" error).

**Comment by davidchase** [comment]
@Klowner which gulp are you using? also note that i am using `vinyl-fs` directly

**Comment by Klowner** [comment]
@davidchase my apologies! I misread your previous comment and thought you were using gulp.

I've been seeing similar issues while working on #121.

Just for example, this only copies 16 of 9000 files and produces an error "The following tasks did not complete: default. Did you forget to signal async completion?"
```javascript
gulp.task('default', function (cb) {
   gulp.src('in/**.png')
      .pipe(gulp.dest('out'))
      .on('end', cb);
});
```

**Comment by davidchase** [comment]
> "The following tasks did not complete: default. Did you forget to signal async completion?"

so you are using gulp v4 ? and ive ran into a similar issue when doing various tests to figure out what my specific issue was and ran into the fact that `dest` didnt emit a `done` and therefore in your case the callback doesnt get called... right?

**Comment by Klowner** [comment]
Oh, perhaps it should be `.on('finish', cb);`.

```javascript
gulp.task('default', function (cb) {
   gulp.src('in/**.png')
      .pipe(gulp.dest('out'))
      .on('finish', cb);
});
Has the same result, 16 files copied and an error about not calling the async callback.

```javascript
gulp.task('default', function (cb) {
   gulp.src('in/**.png')
      .pipe(gulp.dest('out'))
      .pipe(through2.obj(function (file, enc, cb) {
         cb();
      }))
      .on('finish', cb);
});
works fine, copies all 9000 images, and calls the callback on 'finish'.

So it seems as though the behavior has changed from `dest` processing items in the stream regardless of whether there is another "downstream" consumer, to stopping once the high watermark is reached (16).

**Comment by Klowner** [comment]
@davidchase good job on noticing the `stream.resume()`, re-adding it appears to be the fix, AFAICT.

**Comment by davidchase** [comment]
@Klowner doing a `pipe` after your `gulp.dest` because the stream gets drained and data keeps on flowing.

this is the same if you did `.on('data')` or `stream.resume`.

I dont know if adding `stream.resume` back in is the best solution... read how stream-exhaust handles `streams` with `read` methods [stream-exhaust](https://github.com/chrisdickinson/stream-exhaust#prior-art) and in the [source](https://github.com/chrisdickinson/stream-exhaust/blob/master/index.js#L11-L14)

**Comment by Klowner** [comment]
@davidchase ah yes, perhaps the blind `stream.resume()` is a crappy solution.

I've been fiddling around with implementing a `sink()` which accomplishes a similar task.
https://github.com/gulpjs/vinyl-fs/compare/master...Klowner:stream-sink

**Comment by phated** [comment]
We might need to upgrade to streams 3 to have push and pull streams and then make dest a pull stream.

**Comment by davidchase** [comment]
@phated that would be ideal no?

**Comment by phated** [comment]
@davidchase yes, but I am not a streams expert, so I might just be spewing nonsense

**Comment by davidchase** [comment]
@phated can you maybe shed some light on why `dest` is a duplex rather than just a writable? do many people still pipe from the `dest` elsewhere ?

**Comment by contra** [comment]
@davidchase yep, its very common to keep piping to other transforms or other dests

Example:

```js
gulp.src('*.styl')
  .pipe(stylus())
  .pipe(concat('sheet.css'))
  .pipe(gulp.dest('styles'))
  .pipe(cssmin())
  .pipe(rename('sheet.min.css'))
  .pipe(gulp.dest('styles'));
```

**Comment by davidchase** [comment]
@contra gotcha makes sense... thanks for that insight

btw in the [complete](https://github.com/gulpjs/vinyl-fs/blob/master/lib/dest/writeContents/index.js#L35-L37) method what your thoughts on adapting it to do something like:
```js
 function complete(err) {
     var done = stream.push(file);
     if (!done) {
         stream.read();
     }
     cb(err);
 }
```
the stream gets passed in from [saveFile](https://github.com/gulpjs/vinyl-fs/blob/master/lib/dest/index.js#L14-L21) so it refers to the `through` stream

that way when there's a `pipe` you just keep adding the data to the next `transform` or `dest` otherwise just get all of the data out of the buffer... thoughts?

**Comment by contra** [comment]
@phated ^

**Comment by davidchase** [comment]
if this above concept is of interest i can submit a PR :smile:

**Comment by contra** [comment]
@davidchase go ahead and send one and we can discuss more on that
