### ISSUE TITLE
base option possibly not reflecting correct default value

### ISSUE THREAD

**Issue by treshugart** [gulpjs/vinyl-fs#129]
Forgive me if I'm not understanding something correctly here. In the `base` option, you say:

> Default is where the glob begins if any.

This I *think* I understand correctly in that if you specify `something/**` that `base` will be `something` and `**` will be the glob.

However, you also say:

> Default is `process.cwd()` if there is no glob.

What is considered "not a glob"? Is this something that doesn't contain a pattern? An empty string? A relative path? An absolute path?

If an absolute path classifies as a non-glob argument, then if you do something like:

```js
vinylFs.src(['/file/path1.js', '/file/path2.js']);
```

Then the `base` is automatically set as `/file` instead of whatever the current working directory is. That said, I can kind of see the point of this because if you had two completely separate globs that the base path would be ambiguous. But then why have it default at all? The only way a base path could be unambiguous would be if you passed a string glob instead of an array.

In order to get around this you can force the `base` option via the second argument but I'm still wondering if this is the correct behaviour.

**Comment by phated** [comment]
You are specifying absolute paths.  All paths are resolved using node's `path.resolve` method, so if we do `path.resolve(process.cwd(), '/file/path1.js')` it is going to result in the absolute path of `/file/path1.js`.  To make your paths relative, prefix them with `.` or don't put the `/` as is standard unix convention.

**Comment by treshugart** [comment]
I understand the unix convention and node's path resolution semantics but that wasn't my question. My question is: what is considered "not a glob"?

And depending on that answer, why is the `base` reporting as the `dirname` for the files? Shouldn't it be `process.cwd()` like the docs say?

**Comment by phated** [comment]
Anything that doesn't have glob magic is "not a glob".  The `base` property on vinyl objects is resolved by glob2base at https://github.com/gulpjs/glob-stream/blob/master/index.js#L27 but will be switching to glob-parent in https://github.com/gulpjs/glob-stream/pull/56 which has the same behavior.

**Comment by treshugart** [comment]
> Anything that doesn't have glob magic is "not a glob".

So:

> Default is process.cwd() if there is no glob.

Means that `base` should be `process.cwd()` instead of `/file` for `/file/path.js` right?

**Comment by phated** [comment]
No, it gets resolved
