### ISSUE TITLE
Support functions for all options

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#139]
Ref https://github.com/gulpjs/gulp/issues/1450

**Comment by contra** [comment]
I think every single option to src and dest should allow for functions. Right now it's a mixed bag and not a very good API to deal with

**Comment by phated** [comment]
@contra good idea.  I started on a module to normalize these. https://github.com/gulpjs/value-or-function

**Comment by hgwood** [comment]
I've started working on this.

**Comment by contra** [comment]
@hgwood Looking forward to the PR - thanks!

**Comment by phated** [comment]
@hgwood awesome, thanks!  I started implementing the `value-or-function` but I wasn't happy with the code I was writing so I'm excited to see what you come up with.

**Comment by hgwood** [comment]
Some personal stuff has gotten in the way of completing this as soon as I expected. I'll try to open the PR by the end of the week.

**Comment by erikkemperman** [comment]
I just noticed this issue is still open, though I thought the function-value stuff was merged already?

So may as well tack this on here: I was thinking maybe it would be nice to invoke these functions per file, passing it the vinyl each time, rather than just the once?

I am quite swamped this week but have some time freed up in the weekend; if anyone thinks it's a worthwhile idea I might take a stab at it?

**Comment by phated** [comment]
@erikkemperman that's why the issue is still open.  the `.src()` method needs to invoke per file and use the results.  In thinking about this, I needed to open https://github.com/floridoo/gulp-sourcemaps/issues/208

**Comment by erikkemperman** [comment]
Ah, I see. I was thinking it may be useful for `dest` as well, and for consistency maybe do this across the board. I have not looked at gulp-sourcemaps closely, hope they can address your issue!

**Comment by phated** [comment]
I agree but I thought we already did this per file for dest. It's in prepareWrite

**Comment by erikkemperman** [comment]
So it is, i guess I misread the function-value patch.

**Comment by eddiemonge** [comment]
Any movement on this?

**Comment by phated** [comment]
We've hit snags that we are waiting to be resolved. Most of the work is moving to vinyl-prepare where there's more info in the issues.

**Comment by phated** [comment]
Alright everyone.  I think we are closing in on the final stretch with this (I am putting the final touches on https://github.com/gulpjs/vinyl-sourcemap and it's currently usable from github).  If anyone wants to give a hand, it would be really appreciated.  /cc @erikkemperman @hgwood @jonschlinkert @doowb 

If we have to forgo the `vinyl-prepare` stuff to get this shipped, I think I'm fine doing that.  Then, we can revisit later (once we have the best API).

**Comment by erikkemperman** [comment]
So it looks like vinyl-prepare is here to stay.

With respect to this issue: since `passthrough` was removed (https://github.com/gulpjs/vinyl-fs/pull/230) and if/when the through2 options are gone (https://github.com/gulpjs/vinyl-fs/pull/235) I think it is mostly resolved. All options support function values except `resolveSymlinks` (which can't follow the contract, as things stand, because at that point we have glob-results, not vinyls, to invoke the function with).

We might need some tests to nail this shut?

**Comment by erikkemperman** [comment]
Actually, would it be way too opinionated for glob-stream to yield bare-bones vinyls, with just `path` and `base` and `cwd`? Currently it yields plain objects with those same properties, so it might not even break that much.

It would look something like [this](https://github.com/erikkemperman/glob-stream/commits/return-vinyls) -- although I guess it'd then be more properly named "vinyl-glob" or something like that.

It wouldn't change much for vinyl-fs, except to allow `resolveSymlinks` per file: https://github.com/erikkemperman/vinyl-fs/commit/1be8e0d8e957d83a6e53d143beae15626089a45a

It would change the signature for the through2 callback within `vinyl-prepare.src`, making it symmetrical with `dest`, accepting a vinyl: https://github.com/erikkemperman/vinyl-prepare/commit/d12dde52eec1c06d68ae5bacb2dd0f73cbd18d9c

**Comment by erikkemperman** [comment]
Alternatively, without touching glob-stream, much the same would work by reviving wrap-vinyl as a stream stage in `vfs.src`:
https://github.com/erikkemperman/vinyl-fs/commits/revive-wrap-vinyl 
(with the same changes to vinyl-prepare as above).

Sorry for spamming, I'll quiet down for a while.

**Comment by phated** [comment]
@erikkemperman haha, I don't consider it spamming.

I don't think glob-stream should stream vinyl objects (separation of concerns) but I wonder if we can tweak some things to make things more uniform.  I like your `revive-wrap-vinyl` branch; I'll keep an eye out while I refactor.

**Comment by phated** [comment]
Completed by #239
