### ISSUE TITLE
vfs.dest(outfolder, { base.. }) ignores outfolder?

### ISSUE THREAD

**Issue by iliakan** [gulpjs/vinyl-fs#141]
When `dest` has a `base` option, it ignores `outfolder`, right?
Looks like that from the code.

If yes, then maybe let people specify empty `outfolder`?

**Comment by phated** [comment]
can you supply an example of what you are talking about and what your suggestion is?

**Comment by iliakan** [comment]
Well, the example is:
```
vfs.dest('dst', {
  base: 'somewhere'
})
```

Here `'dst'` is ignored totally, the output folder is inferred from `base` option. 
But still `dst` must not be empty.

Actually, I'm a little bit confused about the use case of it. If one wants to use a function to calculate a folder, can use:
```
vfs.dest(function(file) { 
  ...
});
```

**Comment by phated** [comment]
I think the `base` option on `dest()` is a hold over from not accepting a function.  Maybe we can remove it in the 3.0 release.  @contra what do you think?

**Comment by contra** [comment]
@phated I think the fix here is to make the base option work correctly not to remove it. Also open to removing it though if it isn't providing any value

**Comment by phated** [comment]
@contra what is the correct way it should operate if you are using a function for dest?

**Comment by phated** [comment]
@iliakan @contra do you think the correct behavior is:
```js
vfs.dest('./test', {
  base: '/my/base'
});
// Writes files at /my/base/test

vfs.dest('/my/path', {
  base: '/other/base'
});
// Writes files at /my/path
```

This would essentially resolve the dest path from the base path which allows handling of relative paths correctly.  Thoughts?

**Comment by phated** [comment]
Maybe this should just be `path.resolve(options.cwd, options.base, outFolder)` so any relative paths build up to the full path.

**Comment by tmcgee123** [comment]
@phated should this change break tests?

I've developed a test branch with what you commented on above, is this what you were thinking?

https://github.com/gulpjs/vinyl-fs/compare/master...tmcgee123:bugfix/dest-outfolder-141?expand=1

**Comment by phated** [comment]
@tmcgee123 I don't think my last comment was correct.  I'm not sure what the "correct" behavior would be.  Any thoughts?  @contra @iliakan

**Comment by phated** [comment]
Thinking through this some more with @stevelacy, the only example I can come up with where base on `.dest()` would be used would be with liberal globs in `.src()` like:
```js
// src = './client/**/*.sass'
vfs.dest('./dest/styles/');
// => /home/user/project/dest/styles/sass/file.sass
// => /home/user/project/dest/styles/sass/partials/other-file.sass
// src = './client/**/*.css'
vfs.dest('./dest/styles/', {
  base: './sass'
});
// => /home/user/project/dest/styles/file.css
// => /home/user/project/dest/styles/partials/other-file.css
```

However, it seems that this can be solved by using the `base` option in the `.src()` method instead of the `.dest()` method.  I think this option can be removed.
