### ISSUE TITLE
error on grunt-contrib-imagemin since 2.3.0 release

### ISSUE THREAD

**Issue by ryuran** [gulpjs/vinyl-fs#147]
Hello,

Maybe you should know grunt-contrib-imagemin fail with 2.3.0 release. Fixed by use of previous release 2.2.1.
https://github.com/gruntjs/grunt-contrib-imagemin/issues/330

I test with 2.3.0

**Comment by jlescot** [comment]
@ryuran Duplicate of https://github.com/gulpjs/vinyl-fs/pull/142 which is now fixed with https://github.com/gulpjs/vinyl-fs/pull/145
