### ISSUE TITLE
Quirk in passing `read` option from `src` to `through2`?

### ISSUE THREAD

**Issue by erikkemperman** [gulpjs/vinyl-fs#153]
It is unlikely to cause any real trouble, but thought I'd report this anyway:

Wondering if I could provide function values for `src` options like `read` and `buffer`, I just tried my luck. It failed, but in a mildly interesting way...

Turns out that, since the `src` options are passed on to `through2`, I was actually telling the readable streams to invoke my `read` option!

Now I don't know if it actually makes sense to have function values for such options, but I figured that because it means quite different things for `src` and for `through2`, it might be better to not pass this `read` option from one into the other?

And looking at the [commit](https://github.com/gulpjs/vinyl-fs/commit/d553e7474ebb65b89e496dfc3916292b59eec4c2) that introduced this, I am also curious why it passes `opt` instead of the sanitized `options`?

**Comment by phated** [comment]
Just an oversight. Can you create a PR with a failing test and possibly a fix?

**Comment by erikkemperman** [comment]
Probably tomorrow. And would it be a ludicrous suggestion to allow function values?

**Comment by phated** [comment]
I'm still working on that, I'd like to get it in after our fix release that I'm writing tests for.

**Comment by erikkemperman** [comment]
Hm, maybe I had the wrong idea. Thought of this function value of `src.options.read` being invoked for each vinyl object, but people probably expect such an option function to apply to all of them, just like when the option is boolean?

**Comment by erikkemperman** [comment]
PR merged, thanks. Closing.

**Comment by phated** [comment]
Published as 2.4.1 - thanks again @erikkemperman
