### ISSUE TITLE
Empty array in gulp.src

### ISSUE THREAD

**Issue by TrySound** [gulpjs/vinyl-fs#164]
`is-valid-glob` module checks `[]` as invalid. But for example on project start I can have nothing and specify full paths of files with [main-bower-files](https://github.com/ck86/main-bower-files). So I think empty array should be valid.

/cc @jonschlinkert

**Comment by phated** [comment]
No, stop using bad patterns or check the length of the array first. This has already been discussed at length and there are userland patterns you should use to avoid passing an empty array.

**Comment by phated** [comment]
Issues related to this which outline why this is the correct behavior:
* https://github.com/gulpjs/gulp/issues/1298
* https://github.com/gulpjs/vinyl-fs/issues/40
* https://github.com/jonschlinkert/is-valid-glob/issues/3 

I am locking this, as I am in no need of more bikeshed.
