### ISSUE TITLE
Support for symlinks with relative paths

### ISSUE THREAD

**Issue by diagramatics** [gulpjs/vinyl-fs#177]
I've been digging through the code and I can't find any part of the code that allows a relative path on the symlink outputted from `.symlink()`, so apologies if I actually suck at digging around the codebase.

#42 had discussions about having a `mode` option for either an absolute path or relative path and I don't think this got implemented at any point? It'd be awesome if I can get a symlink relative to where the origin file is.

**Comment by vladkens** [comment]
Yep, it's useful opportunity for a cross platform development.

**Comment by versgui** [comment]
Hello,
I read that this feature was intended for 3.0. Any news about the release?
