### ISSUE TITLE
Pass file list as argument to "end" function

### ISSUE THREAD

**Issue by matthewmueller** [gulpjs/vinyl-fs#179]
Not sure how feasible this is, but it'd be nice to be able to get the list of modified/created files out of the pipeline. Not a huge deal since you can just create a transform that collects the files as they pass through, but something like this would be helpful:

```js
vfs.dest(outpath).on('end', function (files) {
  // list of files
})
```

**Comment by phated** [comment]
That would inflate memory usage like crazy, I think.

**Comment by phated** [comment]
Come to think about it, this could be done in userland with a stream that collects the files.
