### ISSUE TITLE
Tests shouldn't need isDarwin check with custom mkdirp

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#183]
It seems that the tests are currently passing with the check still implemented.  Need to look into this.

**Comment by erikkemperman** [comment]
For what it's worth -- I thought it was quirky before the mkdirp merge...

On my mac, the isDarwin distinction was indeed necessary, or the "different modes for files and directories" test would fail. But on my mint linux box I *also*  had to force isDarwin to be true, even though on travis (which I think is a kind of debian?) it works as intended!

I guess we may need to test the mkdirp with masks including the sticky/setuid/setgid bits to see what sticks (ha) on which platforms?

**Comment by phated** [comment]
I've got this __mostly__ figured out.  Just need some feedback on #185 before I commit all the changes.
