### ISSUE TITLE
Change log error regarding `watch`

### ISSUE THREAD

**Issue by npetruzzelli** [gulpjs/vinyl-fs#184]
Should: 

> 5b056f6 update object-assign dep (@contra)
> 27983ef merge (@contra)
> 7ca959e remove watch #92 (@contra)

... be listed under **v2.0.0 (2015/09/25 22:43 +00:00)** instead of **v0.3.14 (2015/09/21 23:57 +00:00)**? Their commit dates occur before 2015/09/21, but the versions are `2.0.0`.

`watch` still exists in `0.3.14` and `1.0.0`. Gulp master (currently `3.9.1`) uses vfs `0.3.14` (glob-watcher `0.0.6`, gaze `^0.5.1`).

As a side note, I am aware that Gulp's v4 branch is using glob-watcher `^3.0.0` (chokidar `^1.4.3`) directly for `gulp.watch`.

Regards

**Comment by phated** [comment]
Probably.  The changelog stuff was done by the community and I don't know how accurate it is.  We are switching to conventional-github-releaser for many other projects and this project will probably be updated.
