### ISSUE TITLE
No Path Specified! Can not get relative.

### ISSUE THREAD

**Issue by HaakonH** [gulpjs/vinyl-fs#190]
My gulp file was working fine then all the sudden I keep getting this error:

\node_modules\gulp\node_modules\vinyl-fs\node_modules\vinyl\index.js:153
    if (!this.path) throw new Error('No path specified! Can not get relative.');

It seems to be failing on my images task. I have verified the source folder exists and there aren't any typos. Any ideas why it might be failing?

gulp.task('images', function () {
  return gulp.src(yeoman.app + '/images/**/*')
    .pipe($.cache($.imagemin({
        optimizationLevel: 5,
        progressive: true,
        interlaced: true
    })))
    .pipe(gulp.dest(yeoman.dist + '/images'));
});

This is part of the Yeoman.io AngularJS default generator.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
