### ISSUE TITLE
Rename a symlink without renaming the target of the link

### ISSUE THREAD

**Issue by lehni** [gulpjs/vinyl-fs#192]
Since https://github.com/ben-eb/gulp-symlink is deprecated now, I am trying to transition to the `vfs.symlink()` method to cover its functionality.

Before, my code looked like this, and it created two symlinks to `src/load.js`, from `dist/paper-full.js` and `dist/paper-core.js`:

```js
    return gulp.src('src/load.js')
        .pipe(symlink('dist/paper-full.js'))
        .pipe(symlink('dist/paper-core.js'));
```

Since `vfs.symlink()` doesn't expect a file as argument but a folder, I am struggling with finding a way to change the symlink's filename. I've tried to use `gulp-rename`, but the result is that the name of both the source and the destination of the link is then changed:

```js
    return gulp.src('src/load.js')
        .pipe(rename({ suffix: '-full' }))
        .pipe(vfs.symlink('dist'));
```

Result:

```
dist/load-full.js -> /.../src/load-full.js
```
Is there a way to overcome this limitation?

**Comment by phated** [comment]
We didn't aim for feature parity with gulp-symlink but instead with `vfs.dest()`.  You will probably need something like gulp-tap and then clone your vinyl objects to get 2 symlinks that point to the same file.  Future support questions should be directed to StackOverflow.

**Comment by lehni** [comment]
Thanks for the swift reply, and apologies for abusing your issue database for a support question.

**Comment by lehni** [comment]
@phated even with that approach, I am still facing the problem that symlinks cannot have a different name for their source and destination. This to me looks like a bug?

**Comment by Dargmuesli** [comment]
Did you find a solution for this, @lehni?
