### ISSUE TITLE
Encoding problem after upload files to server

### ISSUE THREAD

**Issue by marcoskubis** [gulpjs/vinyl-fs#197]
After upload files to server (centos) I get a encoding problem that not occurs when I use Filezilla to send files to server. My local environment is in a Windows machine and I don't know if it is the problem.
Someone had the same problem?

Local/Server
![image](https://cloud.githubusercontent.com/assets/3844716/17122238/1dd54122-52b0-11e6-93ba-b956d3577a5c.png)

**Comment by phated** [comment]
The only encoding that is supported is utf8

**Comment by marcoskubis** [comment]
But it is utf8
