### ISSUE TITLE
Test failure on 2.4.3 with both node v4 and v6

### ISSUE THREAD

**Issue by TheAlphaNerd** [gulpjs/vinyl-fs#199]
```
  1) getTimesDiff makes atime diff undefined if fs and vinyl atime are invalid:
     Error: Expected undefined to equal { atime: undefined, mtime: Fri Jul 29 2016 10:28:55 GMT-0700 (PDT) }
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/fileOperations.js:323:20)
```

**Comment by phated** [comment]
This is due to a lodash "bug fix" that changed behavior we relied on. I've fixed it in master but haven't released yet. Thanks for letting us know.

**Comment by TheAlphaNerd** [comment]
thanks @phated how long do you think it will be before another release? Just figuring out if I should modify what we have going on in citgm CI

**Comment by phated** [comment]
The next release will be a major bump but we have a few more changes to land. Does citgm allow you to modify based on a version range?

**Comment by TheAlphaNerd** [comment]
I can just modify the lookup table to do our tests off of master in the mean time
