### ISSUE TITLE
How to split one stream to many

### ISSUE THREAD

**Issue by jalateras** [gulpjs/vinyl-fs#200]
I was wondering whether someone could provide some best practise for splitting a single stream to multiple streams. I have 1 input file, which i would like to split by NL and create a number of smaller files.  I have created the following to split on NL but i wasn't sure about the best approach to evenly streaming the lines across multiple files.

Would i simply create the destination streams as required and pipe to each of them?

```
var through = require('through2');

function vinylSplit() {
  return through.obj(function(file, enc, done) {
    var buffer;
    if (file.isBuffer()) {
      this.emit('error', new Error('Buffer is not supported'));
    }

    if (file.isStream()) {
      var streamer = through(function(chunk, enc, done) {
        var bufferLast = false;
        var segment = chunk.toString();
        if (buffer) {
          segment =  buffer + segment;
          buffer = null;
        }

        if (segment[segment.length - 1] !== '\n') {
          bufferLast = true;
        }

        var lines = segment.split('\n');
        if (bufferLast) {
          buffer = lines[lines.length - 1];
          lines = lines.slice(0, lines.length - 1);
        }

        lines.forEach(line => {
          if (line.length > 0) {
            this.push(new Buffer(line + '\n'));
          }
        });
        done();
      }, function(done) {
        done();
      });

      streamer.on('error', this.emit.bind(this, 'error'));
      file.contents = file.contents.pipe(streamer);
    }

    this.push(file);
    done();
  });
}

module.exports = vinylSplit;
```

**Comment by phated** [comment]
Your example is fine, but I would probably use something like https://www.npmjs.com/package/split to split your content stream.  Piping contents to another stream and reassigning the new stream to `file.contents` is the correct way to handle this.  There's no need to re-emit the error event, we propagate errors in our `.dest()` method.  In the future, support questions should be directed to StackOverflow.
