### ISSUE TITLE
No path specified!

### ISSUE THREAD

**Issue by HaakonH** [gulpjs/vinyl-fs#204]
I'm suddenly getting this error when trying to build my app using a gulp script that has an "image" task that is failing with this error:

node_modules\vinyl index.js:153                                                                                                                            
    if (!this.path) throw new Error('No path specified! Can not get relative.'); 

Any idea why this might be happening? I did move these files into a new folder with a different name but I updated my bower.json and package.json files with the new folder name.

**Comment by phated** [comment]
One of your plugins is operating on the `.relative` property of a vinyl file but the path was never set.  You'll have to debug your gulpfile.  Support questions should be directed to StackOverflow.
