### ISSUE TITLE
Revisit the naming of `followSymlinks` option

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#205]
This was brought up in https://github.com/gulpjs/gulp/issues/1741

Basically, `vinyl-fs` has an option called `followSymlinks` that reads the contents from the linked file and creates a "hard file" of that instead of a symlink.  If you set the option to `false`, we output symlinks in `dest()`.  This is unfortunately named because it implies we traverse an entire tree of symlinks, which isn't the case because node-glob has a (similarly named) option called `follow` which follows symlinks down a tree; they default this option to `false` because circular symlinks can cause problems.

Our `followSymlinks` option doesn't properly describe what is happening and should probably be renamed in the next breaking release.

@erikkemperman something to keep in mind if you work on the `src` options.

**Comment by erikkemperman** [comment]
I think `resolveSymlinks` might be more descriptive of what it does. Certainly that's something else than what `follow` usually does, as in `node-glob`. Should `resolveSymlinks` (or whatever) check for cycles? Does it make sense to support (move) this option in (to) glob-stream?

**Comment by phated** [comment]
I like that naming suggestion and it differentiates it from `follow` nicely.  I don't think it should check for cycles (how hard would that be?).  It doesn't make sense to move to glob-stream because glob-stream only deals with paths, while `resolveSymlinks` is specific to reading files (vinyl-fs).

**Comment by erikkemperman** [comment]
I must have misunderstood something then. I see that glob-stream itself only deals with paths, but it wraps around node-glob, which does do lots of fs operations... Right?

In fact, I thought that was why you said my moving the glob-stream call to vinyl-prepare was probably not the way to go?

**Comment by phated** [comment]
Correct, the glob-stream call should be piped to vinyl-prepare which should then be piped to a readContents stream.
