### ISSUE TITLE
Really ancient lodash causing NPM warning, package.json has been updated

### ISSUE THREAD

**Issue by ssteinerx** [gulpjs/vinyl-fs#209]
Would it be possible to push a version to NPM with the new dependency on the latest lodash to get rid of the deprecation warning?

Are there any 'must do' tickets before the next release?

Thanks,

ssteinerX

**Comment by phated** [comment]
The latest npm version has a new lodash.  The warning you are seeing is due to gulp 3.x being stuck on a really old version of vinyl-fs.  That version can't be updated because the next version had breaking changes.  The warnings don't really mean anything anyway.

**Comment by ssteinerx** [comment]
Sorry, went back at the dependency tree from the other direction and see that it's a Gulp dependency issue which has several help-wanted issues open in its repo.

My apologies.

ssteinerX

**Comment by ssteinerx** [comment]
I have just filed this: [Gulp #1788](https://github.com/gulpjs/gulp/issues/1788)
