### ISSUE TITLE
The stream only takes the first file matching the globbing pattern

### ISSUE THREAD

**Issue by marcofranssen** [gulpjs/vinyl-fs#214]
Hi I have been trying to read files based on globbingpattern in order to process them from commander.js application.

```javascript
const vfs = require('vinyl-fs');
const map = require('map-stream');
const log = function (file, cb) {
  console.log(file.path);
  cb(null, file);
};
const handle = function (file, cb) {
  console.log('Handling the file %s', file.path);
  cb(null, file);
};

vfs.src(['../some-folder/**/*.xml'])
  .pipe(map(log))
  .pipe(map(handle))
  .pipe(vfs.dest('./output'));
```

However console output looks like this, meaning it only takes the first file from this directory. (Yes there are a lot more `.xml` files in these folders).

```
C:\code\some-folder\some-xmlfile.xml
Handling the file C:\code\some-folder\some-xmlfile.xml
```

So the first file matching does end up in both the piped methods, but the stream simply does not move forward. I took the example from this repo's README.md

**Comment by contra** [comment]
What does gulp-debug at the top of the chain print?

**Comment by marcofranssen** [comment]
Never mind. It was a stupid mistake on my side. The globbing pattern array in above example comes in real life from my commanderjs arguments. Seems commanderjs is already expanding the globbing pattern into a item per file that matches the pattern. On top of that I had a bug that I only took the first element from the array, causing obviously only the first file from the array to be taken. It took me a while with various console logs to figure that out.
