### ISSUE TITLE
Singular glob in an array of globs throws file not found error

### ISSUE THREAD

**Issue by vdh** [gulpjs/vinyl-fs#217]
When using Gulp v4 (using `vinyl-fs@2.4.4`) and a singular glob in an array of globs doesn't match a file, the task fails with an error. The same glob configuration doesn't fail in Gulp v3. For example if `foo.map` exists but `b.json` doesn't, this task:

```js
gulp.task('angry', function testTask() {
  return gulp.src(['*.map', 'b.json'])
    .pipe(gulp.dest('./output'));
});
```

will output:

```
[12:01:43] Using gulpfile ~/Documents/glob-bug/gulpfile.js
[12:01:43] Starting 'angry'...
[12:01:43] 'angry' errored after 45 ms
[12:01:43] Error: File not found with singular glob: /Users/vdh/Documents/glob-bug/b.json
    at Glob.<anonymous> (/Users/vdh/Documents/glob-bug/node_modules/glob-stream/index.js:41:11)
    at Glob.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/Users/vdh/Documents/glob-bug/node_modules/glob/glob.js:172:8)
    at done (/Users/vdh/Documents/glob-bug/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/Users/vdh/Documents/glob-bug/node_modules/glob/glob.js:652:12)
    at /Users/vdh/Documents/glob-bug/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/Users/vdh/Documents/glob-bug/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/Users/vdh/Documents/glob-bug/node_modules/glob/glob.js:728:12)
```

The full reproduction of the issue is in this gist: https://gist.github.com/vdh/89958706d508dfda9b3c8cca8f46feb4

The gist also includes `glob-stream.js` for reproducing the bug without `gulp` or `vinyl-fs`.

**Comment by phated** [comment]
@vdh thanks, perfect.  I'll dig into this when I have some free time.

**Comment by chrisames** [comment]
Did this fix the issue with not being able to concatenate and minify css files?

**Comment by phated** [comment]
@vdh while working on glob-stream, I found that this was by design as per the test at https://github.com/gulpjs/glob-stream/blob/master/test/main.js#L555-L562 - however, I don't think that is the best behavior and will be revisiting it before the next major release of glob-stream.  @contra do you have an opinion either way?

**Comment by phated** [comment]
After further thinking, I think that it should always throw on a singular glob missing.  You can set `{ allowEmpty: true }` in the options as per https://github.com/gulpjs/glob-stream/blob/master/index.js#L126

**Comment by vdh** [comment]
@phated That seems counter-productive. A glob is just supposed to build a list from a possible range of matching patterns. You could argue the case for an error if that _resulting list_ is empty, but it is not the domain of a glob utility to pedantically audit everyone's configuration against their file system.

If a file is important enough to someone's setup that an error should be thrown if it's missing, then _that person's_ configuration logic should address the scenario, by checking if the file exists. It's inelegant to bake that sort of use case assumptions into the guts of a glob utility. _Especially_ when it's an undocumented breaking change from the previous release of Gulp.

**Comment by phated** [comment]
Everything is undocumented because we haven't shipped. You can build a glob with your singular file included and it will also solve your problem.
