### ISSUE TITLE
encoding param

### ISSUE THREAD

**Issue by contra** [gulpjs/vinyl-fs#23]
should work on src and dest, default being utf8

**Comment by czbo** [comment]
I am currently trying to use gulp.src to read and transform html files with Chinese (big5) characters into utf8 encoding. Doesn't seem completely straight forward; still trying to figure it out...

**Comment by czbo** [comment]
Follow up to my own comment yesterday: I am able to figure out how to read in a file with big5 encoding and output to utf8 encoding. It doesn't work if I simply specify {encoding: 'utf8} in the .dest function; I need to use convertEncoding to process the Stream and then do other things. It seems to work the same even if the option {encoding:'big5'} is omitted in the .src function.

<other required plugins omitted...>
var convertEncoding = require('gulp-convert-encoding');
gulp.task('encode', function () {
  return gulp.src('app/**/*.html',{encoding: 'big5'})
    .pipe(convertEncoding({from: 'big5', to: 'utf8'}))
    .pipe(gulp.dest('.tmp'))
});

**Comment by phated** [comment]
@contra do you have any thoughts on how to implement this?

**Comment by contra** [comment]
Haven't looked into it yet - one thing to keep in mind is concating files of multiple encodings together. I've been wrangling with some issues in gulp-concat about that.

**Comment by phated** [comment]
maybe vinyl should have an encoding property that plugins like gulp-concat could check and emit an error if they see different encodings?

**Comment by phated** [comment]
@contra any thoughts on my comment above?

**Comment by alvieirajr** [comment]
https://www.npmjs.com/package/gulp-convert-encoding

**Comment by phated** [comment]
What does this API look like?  Was thinking about implementing with `iconv-lite` which would give us a stripBOM replacement too but I don't have a good sense of how this works.

**Comment by phated** [comment]
@contra I'm thinking we should consider shipping the encoding support that Erik already has completed in #287

**Comment by contra** [comment]
@phated I agree - the PR looks good to me and seems like a minor release which is nice. Is the only outstanding item to propagate the new option docs to the main docs?

**Comment by phated** [comment]
I'd be more comfortable releasing it in the major to avoid any weird edge cases we haven't considered.
