### ISSUE TITLE
how to exclude folder but keep two or more 

### ISSUE THREAD

**Issue by lordisback** [gulpjs/vinyl-fs#241]
I have a project like this, 
root
  |-incl1
  |-incl2
  |- ...
  |-excl1
  |-excl2
     |- .gitignore  <-- keep this one
     |- some.json < -- keep this one too
     |- (other files)  <-- exclude them

when I test this , it will work
`gulp.src([
    baseDir + '/**',                              // Include all
    '!' + baseDir + '/excl1{,/**}',               // Exclude excl1 dir
    '!' + baseDir + '/excl2/**/!(.gitignore)',    // Exclude excl2 dir, except .gitignore
], { dot: true });`

but if I do like this , it break
`gulp.src([
    baseDir + '/**',                              // Include all
    '!' + baseDir + '/excl1{,/**}',               // Exclude excl1 dir
    '!' + baseDir + '/excl2/**/!(.gitignore)',    // Exclude excl2 dir, except .gitignore
    '!' + baseDir + '/excl2/**/!(some.json)' , // Exclude some.json too
], { dot: true });`

I found some ref on [stackoverflow](http://stackoverflow.com/questions/26485612/glob-minimatch-how-to-gulp-src-everything-then-exclude-folder-but-keep-one), but it's not work for me.
what can I do?

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
