### ISSUE TITLE
Attach symlink property to Vinyl objects when passed through `symlink` method

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#249]
As per @erikkemperman's comments in #246, we should be attaching the `.symlink` property in other scenarios (other than just `src(..., { resolveSymlinks: false })`).  The most obvious of these is when the file passes through the `symlink` method and a symlink is created (I think this can be done in symlink's `prepare` stream to reduce some path history hackiness).

**Comment by erikkemperman** [comment]
That's exactly what I'd done earlier but never got around to submitting: attach `symlink` property before changing `file.path` in prepare, and then use that instead of `file.history[-2]`.

**Comment by phated** [comment]
Feel free to submit it if you get a chance. I'm not tackling this currently.

**Comment by erikkemperman** [comment]
Will do, as soon as I find some time!

**Comment by erikkemperman** [comment]
@phated I think the `file.symlink` property should be absolute, like `file.path`, even for relative links. Does that sound right?

**Comment by erikkemperman** [comment]
Hm on second thought I'm not sure: `src` just attaches the result of `fs.readLink` for symlinks, which might be relative.

**Comment by erikkemperman** [comment]
Thanks for review and merge! Sorry about the bogus refs above, guess I shouldn't include issue ids until the commit is final.
