### ISSUE TITLE
Review naming of `relative` option in `symlink` and `dest`

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#251]
The name of this option is really confusing.  I think it should be renamed so it makes more sense across methods.

Maybe something like `relativeLinks`

**Comment by erikkemperman** [comment]
To keep things consistent with `resolveSymlinks` maybe it should be `relativeSymlinks`? That would get a bit verbose though so alternatively all of them could just end with `..Links`?

**Comment by phated** [comment]
I like `relativeSymlinks`

**Comment by erikkemperman** [comment]
👍🏻
