### ISSUE TITLE
symlink on Windows generating EPERM 

### ISSUE THREAD

**Issue by BurtHarris** [gulpjs/vinyl-fs#262]
I've written a gulp task to `symlink` (really junction) my project directory into __test/node_modules__ to allow the tests to run wile requiring my package by name.   As I read the docs, they say `symlink` should really create a junction on windows, so it shouldn't require elevated permissions.

__Code (in gulpfile.js)__
```javascript
const vfs = require('vinyl-fs');
...
/**
 * Install a symlink in test/node_modules/core-decorators to allow tests to run
 */
gulp.task('symlink', function () {
  return vfs.src('.')
    .pipe(vfs.symlink('test/node_modules/core-decorators'));
});
```

__Observed behavior (on Windows 10)__

```
[17:12:05] Using gulpfile C:\code\core-decorators.js\gulpfile.js
[17:12:05] Starting 'symlink'...
[17:12:05] 'symlink' errored after 17 ms
[17:12:05] Error: EPERM: operation not permitted, symlink 'C:\code\core-decorators.js' -> 'C:\code\core-decorators.js\test\node_modules\core-decorato
rs'
    at Error (native)
```
__Version in use__

```
PS C:\code\core-decorators.js> npm ls vinyl-fs
core-decorators@0.19.0 C:\code\core-decorators.js
+-- gulp@3.9.1
| `-- vinyl-fs@0.3.14
`-- vinyl-fs@2.4.4
```

Could my code (running in gulp) be getting the old version of vinyl-fs?

**Comment by BurtHarris** [comment]
This succeeds if I elevate permission to administrator, which leaves me to believe its really trying to use symlink rather than an NTFS junction point.

**Comment by phated** [comment]
The junction code hasn't shipped yet. It's going in 3.0 of vinyl-fs. Install from master.

**Comment by BurtHarris** [comment]
@phated you sure are quick to close issues.   The other bugs I've filed are because I can't get master to build and test, but my real effort is the one that needs links.   Why close this when I still don't have a workaround?

**Comment by BurtHarris** [comment]
I started this adventure from https://www.npmjs.com/package/gulp-symlink/, which suggested I use vinyl-fs directly if I'm still on gulp 3.x.   That workaround doesn't work.

**Comment by erikkemperman** [comment]
@BurtHarris master builds fine in Windows, or else the Appveyor CI would've complained. Can you try if you can get your git client to stop messing with line endings?
