### ISSUE TITLE
jscs errors: Invalid line break on Windows 10

### ISSUE THREAD

**Issue by BurtHarris** [gulpjs/vinyl-fs#263]
I just cloned the repo and ran `npm install` followed by `npm test`.   The later gave me a bunch of lint errors, all similar to the first one:

```
C:\code\vinyl-fs>npm test

> vinyl-fs@2.4.3 pretest C:\code\vinyl-fs
> npm run lint


> vinyl-fs@2.4.3 lint C:\code\vinyl-fs
> eslint . && jscs index.js lib/ test/

Invalid line break at index.js :
     1 |'use strict';
---------------------^
     2 |
     3 |module.exports = {
```

**Comment by BurtHarris** [comment]
Versions:
'''
C:\code\vinyl-fs>node -v
v6.11.1

C:\code\vinyl-fs>npm -v
3.10.10

C:\code\vinyl-fs>eslint -v
v4.3.0
'''

**Comment by BurtHarris** [comment]
Seems like this project is using a very old version of eslint.   I see discussion in gulpjs/eslint-config-gulp#10 related, not sure why that issue was closed however.   

While I understand support for Node 0.10 might be desirable, it seems like might be the source of some gridlock.

**Comment by BurtHarris** [comment]
Oh, I see, this isn't `eslint`, it's `jscs`.

**Comment by phated** [comment]
We use old versions of both to support node 0.10

**Comment by BurtHarris** [comment]
@phated  Is it really important to support building the package on such an old version?   

Note I'm not questioning that the package should _run_ on older versions, but build dependencies don't need to impact runtime.   It would just take a slightly tricky CI environment to build on a modern node.js, then test on an older version.

**Comment by BurtHarris** [comment]
@phated why close this issue?   

You've explained why you are still using jscs, but done nothing about the errors I get when clone, build and test.   It may be something different about my git setup, but the solution is still unclear.

**Comment by erikkemperman** [comment]
@BurtHarris You may have set up your git client to transform line endings to native?

Perhaps we should add a `.gitattributes` file to the repo to enforce the right one, but the default settings appear to not cause any trouble on Appveyor.

**Comment by erikkemperman** [comment]
Foe what it's worth, I think it's fine to enforce proper line endings by the way, and personally I prefer unix over windows endings. It helps keep the repo consistent (have you ever seen a file in vi after it was touched by a windows user?) and avoids obfuscating things like git blame just because an editor on windows decides it wants to fix eols :-)

**Comment by BurtHarris** [comment]
> You may have set up your git client to transform line endings to native?

I don't really remember changing it, but `git config -l` tells me `core.autocrlf=true`.

@erikkemperman I agree that enforcement of a chosen line endings standard ___in the repository___ is a fine thing.   I believe __git__ does that by default, its certainly what `core

None the less, my chosen editor ([vscode](https://code.visualstudio.com/)) has no problem with either style, and generally tries to preserve what it finds in the file system (as I do as well.)  I've not seen problem with other open source project, so this surprises me a bit, especially to have this issue closed without resolution.

That said:

- I agree that __.gitattributes__ may be the best solution to address this, but I've tried modifying it so far no joy, but I'll look into further if this issue is re-opened  (no point in my digging if the project has an embedded unix bias, I'm an old dog, my os isn't changing.)

- This project has an [__.editorconfig__ ](http://editorconfig.org/), but it lacks any indication of preference for unix-style newlines.   If the choice is made to enforce line-endings in contributors file systems, this needs to be changed.

- The tool raising objections, [__jscs__](https://github.com/jscs-dev/node-jscs) is clearly marked as __unmaintained__, and even upgrades to jscs (3.x) haven't been incorporated into this project.   While I have no experience with the tool, my guess is that a rewrite of the rules might have relaxed its treatment of line endings.   I do know that eslint doesn't enforce line-ending styles by default.

This last part, not upgrading build tools, suggests to me that there's a __gulpjs__ project governance choice (re support for node.js 0.10) that could be slowing down progress here and limiting contributors.  I asked @phated a clarifying question about support for running on node.js 0.10 vs. building on it.   Do you have an opinion on that?

**Comment by erikkemperman** [comment]
If I remember correctly, changes to `.gitattributes` don't take effect until you `git add` the file (it's not in the repo currently) much like `.gitignore`. And even then I think it governs transfer to/from the remote, so might not resolve the lint errors if your files were already changed.

About supporting node 0.10, I personally could live without it but I know @phated wants to keep it around and presume he's got solid reasons for that.

As to dependencies generally, I think we should be at the latest versions compatible with the node engine baseline where possible, but AFAIK there's no automatic checks around that. Maybe something like greenkeeper.io would help?

Having different version ranges for running and testing, if that's what you were proposing, sounds like a bad idea on almost axiomatic grounds... So probably I misunderstand you there?

Having said that, I get that it's frustrating if a cosmetic glitch gets in the way of your playing around with master. But it helps make sure PRs comply with style without further review. The benefits outweigh the costs, imho.

**Comment by BurtHarris** [comment]
> Having different version ranges for running and testing, if that's what you were proposing, sounds like a bad idea on almost axiomatic grounds... So probably I misunderstand you there?

Perhaps I wasn't clear.   I meant to say different platform versions for _building_ and testing.   For example I'm saying that the build tools (e.g. __eslint__ and/or __jscs__) only need to run once per OS, and that can be on a modern, supported (LTS) build of node.js.   Tests on the other hand should run on each supported version of node.js.    

Any confusion may be because there's no transpiler used in this project.   Instead of _building_ I might have said _linting_, which probably simplifies doing what I'm suggesting here.    In practical terms, I'm suggesting is that the `pretest` script could be removed from _package.json_, and the `lint` script run only if the current node.js build supports the latest version of all the linting tools used.    This

**Comment by erikkemperman** [comment]
Ah, I see. The CI config would get a bit tricky though, right? I'd probably prefer avoiding the whole mess with git attributes...

**Comment by BurtHarris** [comment]
I think they are separate issues.   Tools out-of-date is a smell, even if there were no problem with line endings.

**Comment by erikkemperman** [comment]
They are separate, but only the line-ending thing is immediately obstructing your running master, right? And I'm pretty sure that's due to your git setup, not this repo?

**Comment by BurtHarris** [comment]
Yes to your first question, sort of.  

But no, I disagree with your root-cause analysis.  What I'm saying is that the root cause of the line ending thing is that `package.json` in this repo specifies unsupported and obsolete tools that are incompatible with a perfectly valid __git__ setup (`core.autocrlf=true`) that is commonly used on Windows.      Upgrading the tools to more modern ones not incompatible `core.autocrlf` (as done in PR #265) has unblocked me as effectively as changing my git settings does; and it has the the added benefit of starting to address the code-smell of getting blocked on obsolete tools.  (Note the change I made in #265 does not break node.js v0.10.0 scenarios.)

What I don't understand is if closing this issue without a resolution was intended to justify punting #265 or something similar.

**Comment by phated** [comment]
Closing this was a mistake I made from mobile.  We should resolve this, but I'm not sure the proper way.  Please stop calling our tools a "code-smell", as they are chosen specially to support our node 0.10 support requirement (and yes that includes running the same CI on all node versions).

**Comment by BurtHarris** [comment]
Thanks for reopening @phated.   

Sorry if I offend describing the dependency on jscs as a smell, perhaps [software brittleness ](https://en.wikipedia.org/wiki/Software_brittleness) would be a more palatable term.   I think it applies when simple things like line endings are getting in the way:

> Software brittleness is the increased difficulty in fixing older software that may appear reliable, but fails badly when presented with unusual data or altered in a seemingly minor way.

The boundaries of your definition of "CI" are a bit unclear to me.   Despite what the "CI services" might have you believe, integration is something that developers do, not these services.   What these services do are provide environments to run tests as part of integration.   

Personally, I don't consider linters to be tests, they are code quality tools best run integrated in the developer's IDEs.   Of course it makes sense to run them centrally as part of the check-in process to double-check, but as long as they are run consistently, there's no advantage to running them on all node versions.   If you are open to that, I'll prepare a PR proposing something more specific.

**Comment by BurtHarris** [comment]
As an example, of how what I'm suggesting can be implemented using supported CI configuration features:  https://github.com/yarnpkg/yarn/blob/master/.travis.yml#L33.   There is an explicit mapping of what steps get run on what versions of node, good stuff.   For that project, lint only gets run on nodejs version 6.

**Comment by erikkemperman** [comment]
@BurtHarris Interesting. They do not, as far as I can see, do the same on [Appveyor](https://github.com/yarnpkg/yarn/blob/master/appveyor.yml)? But perhaps more importantly, doing something like this -- in order to upgrade dev-dependencies -- will mean that we can't locally run `npm test` on node 0.10. I'm guessing @phated will not want to do that?

**Comment by phated** [comment]
As @erikkemperman noted, I run my `npm test` locally on node 0.10 (least common denominator) so I'm not open to changing the workflow to not work in my environment.

**Comment by BurtHarris** [comment]
@phated My solution would include removing the `pretest` script from package.json, so it wouldn't break in your environment.    To make up for that, I'd run `npm run lint` in the CI environments, but this can be limited to the `nodejs` latest build.    That way you can upgrade eslint to the latest.

**Comment by phated** [comment]
But I want `npm test` to run linting because sometimes I code with linting off in my editor...

**Comment by BurtHarris** [comment]
I understand but that's the source of software brittleness I've been talking about.   Testing is different from code quality tools.   NPM doesn't have a built-in lifecycle command for code quality tools, so we use something like `npm run lint` or `npm run build` for them.   Lumping them in with tests is sloppy.

**Comment by phated** [comment]
It's not sloppy; it keeps everything self-contained to the `npm test` pattern (a common npm ecosystem pattern) and avoids people needing to configure their environment to handle linting, etc.

The pattern for development of npm modules should be:
1. `git clone <project>`
2. `npm i`
3. edit
4. `npm test`
5. `git push`

And should not require any other configuration or knowledge of tools.  I'm sorry line-endings tripped up your experience with this but we have a pattern that we'll be applying to every gulpjs repo.

**Comment by BurtHarris** [comment]
But it has you stuck on an ancient version of eslint!

I've submitted my suggestion as PR #270.

**Comment by phated** [comment]
"ancient" is such a toxic term in the JS community.  It pains me so much 😭 

The version of gulp people rely on daily is like 3-4 years old.  You wouldn't call a child of 3-4 "ancient"

**Comment by BurtHarris** [comment]
I'm sure you know much more about the JS community than I do.    But I've been in the software development community for over 40 years now, so I'm happy to label myself ancient too if that helps.    

The difference is that humans are antifragile, they can learn from things being broken.   Software can't do that, at least not today.

**Comment by erikkemperman** [comment]
Semantics of "ancient" aside, the salient thing here seems to me to be the fact that one of the dependencies is _unmaintained_.

Do we know what it is about newer eslint that doesn't work on 0.10? Would it be totally quixotic to see if we can't work with them and remedy this at their end?

**Comment by erikkemperman** [comment]
OK, that's a resounding [no](https://github.com/eslint/eslint/issues/4483).
