### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by vajahath** [gulpjs/vinyl-fs#276]
We need to update dependencies. This shows up while installing gulp:
```
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible.
```
:)

**Comment by allan-simon** [comment]
@phated  for people like us that don't have the full context, can you explain us why this issue is auto-closed ?  I'm facing currently the same problem as @vajahath

**Comment by allan-simon** [comment]
after a little search, for those that like me come from google to here: https://github.com/gulpjs/gulp/issues/1604
basically updating is not that simple and the problem is currently being tackled

**Comment by Mr-Henderson** [comment]
indeed I am searching how to upgrade and solve minimatch https://nodesecurity.io/advisories/118  so I was looking for that mini match file in the tree from npm audit to clear the security vulns, yet its either hidden or I have zero clue wtf Im doing. Any help would be greatly appreciated I will share the info to help 100s of others stuck on this thanks. :)
