### ISSUE TITLE
Can I propose a little fix for 0.3.14: chmod always applied even when not needed

### ISSUE THREAD

**Issue by olivier-monaco** [gulpjs/vinyl-fs#280]
Hi,

I know the v0.3.14 is old... very old... but gulp 3.x depends on it.

There's a little bug in lib/dest/writeContents/index.js, line 27 of this version. We compare the current file mode restricted to the last 3 octal-digit with the full required mode. This bug is fixed in 2.0. If I provide a pull request, is there a chance you package a 0.3.15 to fix gulp?

The fix is just to change ligne 27 to:
```js
      if (currentMode === (file.stat.mode & 4095)) {
```

This fix is required when different users run the same gulp on a unix box. Otherwise a EPERM error occurs on chmod.

Thanks,

Olivier

**Comment by phated** [comment]
@olivier-monaco we aren't backporting things because 0.3.x doesn't have a good test suite and we don't want to unintentionally break things.  Feel free to depend on the new vinyl-fs directly, it works the same way with gulp 3.x, but just be aware of the breaking changes.
