### ISSUE TITLE
Rebase review!!!

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#284]
@stevelacy @contra @erikkemperman @terinjokes 

I've just finished the 3.0 rebase at https://github.com/gulpjs/vinyl-fs/commits/rebase-3.0 - please please please do a thorough review of said rebase.  Once I get some sign-offs, I'll re-tag all the releases, publish all the changelogs, force push to master and release 3.0

**Comment by terinjokes** [comment]
Hey @phated!

I can take a look. Do you have recommendations for things I should be keeping my eyes peeled for?

**Comment by phated** [comment]
* Make sure I didn't hijack any commits from people (when I split commits apart, etc)
* Verify the messages make sense
* Check my conventional changelog prefixes
* other stuff?

**Comment by erikkemperman** [comment]
@phated Final push, excellent! The commit messages look fine, and I quickly diffed against master to find all is the same, as expected (well, except for version in package.json.)

LGTM!

**Comment by stevelacy** [comment]
I found three commits that seem to have author issues, especially since there were prior and later commits with their correct authorship.
https://github.com/gulpjs/vinyl-fs/commit/1f085e04ee92e3d6923b0cc72c1f6bd50b95a72b
https://github.com/gulpjs/vinyl-fs/commit/c196935e0063264eb217111cf2031d7fee88b107
https://github.com/gulpjs/vinyl-fs/commit/bcfd3423d36059143960a6d08fda88673bc383bd

**Comment by erikkemperman** [comment]
@stevelacy Just a guess, but I think those might be GH accounts that no longer exist?

**Comment by stevelacy** [comment]
They would be linked to the @ghost account if there were deleted.

It seems that some of the contributors do not have their correct email linked to github: 
https://github.com/oconnore/vinyl-fs/commits/master
https://github.com/vineethawal/vinyl-fs

**Comment by phated** [comment]
I'm not going to fix random contributor's emails that they deleted in their GitHub settings.

**Comment by stevelacy** [comment]
No worries, everything else looks good

**Comment by phated** [comment]
Alright all.  I'm shipping this today.

**Comment by phated** [comment]
Release created in https://github.com/gulpjs/vinyl-fs/commit/48c7141be9a378aebeea79bad0ce65a9038ec800 

Waiting on CI before publish.

**Comment by phated** [comment]
Whoops, rolling that back. There's some skipped tests that I needed to make work and those were breaking.

**Comment by phated** [comment]
Published!

**Comment by erikkemperman** [comment]
@phated 
Congrats on the 3.0.0 release, and thanks for persevering!

Quick question, what's your idea about the "closed by rebase" PRs? I could try updating some (I'd especially hate to see the encoding effort buried) but then again if you prefer to forget about them for awhile that's cool too.

**Comment by erikkemperman** [comment]
@phated Nevermind, just saw https://github.com/gulpjs/vinyl-fs/pull/257#issuecomment-349418127

**Comment by phated** [comment]
@erikkemperman yeah, sorry about that.  I realized too late that I should change the base branch for the open PRs :frowning_face:

**Comment by erikkemperman** [comment]
No worries, had to resolve a bunch of conflicts either way :-)
