### ISSUE TITLE
No CHANGELOG entry for 3.0.0

### ISSUE THREAD

**Issue by BurtHarris** [gulpjs/vinyl-fs#289]
I saw you've bumped the major version to 3.   That seemed interesting enough to have a look.

I checked the *CHANGELOG.md* and was surprised to find no entry explaining what 3 major version change signified.   I assume there are breaking changes, but was hoping for a high-level summary..

**Comment by phated** [comment]
Changelogs are done in the GitHub release tab now. Thanks for pointing out that I left the changelog file in the repo, I'll remove it.

**Comment by phated** [comment]
Done.
