### ISSUE TITLE
Error: File not found with singular glob

### ISSUE THREAD

**Issue by Munter** [gulpjs/vinyl-fs#292]
When sending in an array of glob patterns to `vinylFs.src` and one of the patterns yields no results, this error is thrown: `Error: File not found with singular glob: <path/glob> (if this was purposeful, use 'allowEmpty' option)`

In Gulp 4 this error is thrown and breaks previously working pipelines.

According to https://github.com/gulpjs/gulp/issues/1298#issuecomment-260508707 this error should only be thrown when the sum of all the globs yields and empty array, not when a single individual glob yields and empty array.

Reproduction:

```js
const vfs = require('vinyl.fs');

vfs.src([
  '*', // Has matches
  'sdalkjdsflkjdslkjadslk' // Has no matches
]);
```

Expected result: A stream with an array of files matching the `'*'` glob.

Actual result: Throws `Error: File not found with singular glob: <path>/sdalkjdsflkjdslkjadslk  (if this was purposeful, use `allowEmpty` option)`

In Gulp 4 there is no way to pass `allowEmpty`, so this problem cannot be worked around

**Comment by phated** [comment]
Hey @Munter - this behavior is expected and defined in glob-stream's tests at https://github.com/gulpjs/glob-stream/blob/master/test/index.js#L657-L667

We briefly investigated supporting your use case but it wasn't possible to do while keeping our stream API + handling ordered globs + handling ordered glob negation.  I've updated my comment in that thread to reflect this outcome.

> In Gulp 4 there is no way to pass allowEmpty, so this problem cannot be worked around

That statement is incorrect.  You specify options like `gulp.src(badInvalidGlobs, { allowEmpty: true })`

**Comment by Munter** [comment]
Thank you for the quick follow up. I ended up figuring out that the original dependency on the optionally available file could be completely removed, but I'll keep this in mind for next time :)

Thank you for all your work

**Comment by phated** [comment]
Glad you figured it out.  We found that often patterns like this were unintentional or better served with different patterns, which is why we implemented this change.

**Comment by Komald** [comment]
@Munter Hey can you please tell from where we can remove the original dependency? I am also facing similar issue with vendor.css
