### ISSUE TITLE
Write fails if stream is piped after vfs.dest

### ISSUE THREAD

**Issue by viveleroi** [gulpjs/vinyl-fs#293]
Using vinyl-fs 3.0.1.

I'm trying to pipe the stream *after* `vfs.dest` has run so that I can log the *final* file path, yet I'm noticing that it consistently interrupts the file write process.

I've tried listening for stream `error` events after both phases, with no luck. I've used try/catch around my log code and no errors are thrown. 

After adding nothing but a console.log to the method, it's not even firing for half of my files and they're never written.

However, by ensuring `vfs.dest` is the last piped method, the write works consistently without fail.

```js
stream = stream.pipe(vfs.dest(conf.output));

stream = stream.pipe(through2.obj((file, encoding, cb) => {
    if (!file.isNull() && opts.verbose)) {
        const relativePath = file.path.replace(process.cwd() + '/', '');

        console.log(chalk.green(`Writing ${relativePath}`));
    }
}));
```

**Comment by phated** [comment]
please supply a full example, not a subset of your code.  We have tests for what you are trying and they pass.

**Comment by phated** [comment]
The following works - You multiple typos/problems in your through2 stream body.
```js
var gulp = require('gulp');
var through2 = require('through2');

gulp.task('test', function test() {
  var stream = gulp.src('./src/*.js');

  stream = stream.pipe(gulp.dest('./dest'));

  stream = stream.pipe(through2.obj((file, encoding, cb) => {
      if (!file.isNull() && opts.verbose) {
          const relativePath = file.path.replace(process.cwd() + '/', '');

          console.log(`Writing ${relativePath}`);
      }

      cb();
  }));

  return stream;
});
```
