### ISSUE TITLE
dest() result stream does not end when writing a stream using Node 9

### ISSUE THREAD

**Issue by mgroenhoff** [gulpjs/vinyl-fs#295]
When writing a stream (`file.isStream()` return `true`) using `vfs.dest()` the resulting stream will never end. I did some digging and it seems the code inside `file-operations.js` is out of date with when compared to Node 9.

The issue is on the folowing line:
https://github.com/gulpjs/vinyl-fs/blob/e739f6c62ef69f53fe9ca210cbc79ac548ec1bf2/lib/file-operations.js#L376-L377

When i compare this to Node 9:
https://github.com/nodejs/node/blob/8c00a809bc08d87776f74c84751607155f3df61f/lib/fs.js#L2462-L2467

It calls destroy instead of close (which btw is not even part of the public API). When i change it to `this.once('finish', this.destroy);` (like Node does) everything seems to works fine.

**Comment by phated** [comment]
As I stated in the other thread:
> unfortunately, we don't support node 9 because the node team doesn't seem to care that they keep breaking userland.

The logic you are referencing was pulled out of an LTS version of node and has worked across all versions until 9.  We can't keep bending to node-core's whim when we also have to think about backwards compat.
