### ISSUE TITLE
onWritten is not defined

### ISSUE THREAD

**Issue by jonschlinkert** [gulpjs/vinyl-fs#298]
https://github.com/gulpjs/vinyl-fs/blob/master/lib/symlink/link-file.js#L30

**Comment by phated** [comment]
ping @erikkemperman  - I'm not sure which callback it's supposed to call there.  I believe this was pulled from another chunk of code by erik

**Comment by phated** [comment]
Looks like it should just be `callback` and was pulled from https://github.com/gulpjs/vinyl-fs/blob/master/lib/dest/write-contents/write-symbolic-link.js#L28-L31

**Comment by jonschlinkert** [comment]
fwiw it didn't cause me any problems, I didn't have time to write more earlier. I just noticed it in the code and wanted to let you know. 

As much as we all like to act like code snobs about stuff like this, it happens to everyone. Linters are still run by humans lol.

**Comment by phated** [comment]
No worries.  Our linting setup needs a lot of work.

**Comment by erikkemperman** [comment]
https://github.com/gulpjs/vinyl-fs/pull/299

Indeed, this looks like a sloppy/paste from `dest` to `symlink` on my part. Apologies, I do usually try to take note of lint output!

Also, this path is apparently not covered by the tests -- or we would have caught this obviously -- but I didn't have time to remedy that just now. For what it's worth, we get here only on Windows, when creating a symlink to a target which exists but can't be statted (as in permissions, I guess).

**Comment by erikkemperman** [comment]
PS thanks @jonschlinkert for reporting this -- much better to address this before it actually burns anyone.
