### ISSUE TITLE
Node 10 broke some of our mode tests

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#300]
Ref https://travis-ci.org/gulpjs/vinyl-fs/jobs/378478047

I'm rolling back the build matrix for now.

**Comment by nikolowry** [comment]
Can confirm on my ArchLinux box, had to roll back to 9.11.1.

Experienced `Uncaught RangeError [ERR_OUT_OF_RANGE]: The value of "mode" is out of range.` when running a gulp task that was copying a src directory with a large-ish amount of children.

**Comment by phated** [comment]
I believe node's fixed this now

**Comment by phated** [comment]
They fixed the `mode` stuff but they broke our `closeFd` tests.  I've put in a patch that fixed that at https://github.com/gulpjs/vinyl-fs/commit/6aef383e8a831b7cd7f209be4caf1ee92d15b4f7
