### ISSUE TITLE
Error: Received a non-Vinyl object in `dest()`

### ISSUE THREAD

**Issue by soumyash** [gulpjs/vinyl-fs#301]
When i try gulp build, it fails with the error "Error: Received a non-Vinyl object in `dest()` "
I am using gulp (CLI - 2.0.1 and gulp local - 4.0.0)
i installed gulp using - npm install gulp@next

NODE - 4.9.1
NPM - 2.15.11

I am running these commands on Ubuntu 14.04 version.
Let me know if you need more information.

**Comment by phated** [comment]
Sounds like you are somehow ending up with an old version of vinyl-fs - we, long ago, released a patch version that fixed this issue.

**Comment by chetanakki** [comment]
I am using gulp ngdocs with gulp 4 and receiving the same error.
Dependency of vinyl-fs 

├─┬ gulp@4.0.2
│ └── vinyl-fs@3.0.3 
└─┬ gulp-ngdocs@0.3.0
  └── vinyl-fs@0.3.7
Can someone help to fix this?
