### ISSUE TITLE
Create symlink with different name than destination

### ISSUE THREAD

**Issue by chriskinsman** [gulpjs/vinyl-fs#303]
I have a directory structure like:

www
|-src-public

I want to create a symlink in www named public that points to src-public.

I can't figure out how to do this.  The following code is what I believe should work:

    return vinylfs.src('./src-public', {followSymlinks: false, relativeSymlinks: true})
        .pipe(vinylfs.symlink('./public'));

Instead it creates a new directory public under www and puts a symbolic link named src-public in it that points to www/src-public.

What is the proper way to do this?

**Comment by phated** [comment]
I think you need to glob

**Comment by erikkemperman** [comment]
This was also, tangentially, discussed in https://github.com/gulpjs/vinyl-fs/issues/245 but with no clear resolution I think.

Personally I think we ought to support symlinks with different basenames somehow but I don’t know what the API would look like.
