### ISSUE TITLE
 Error: Received a non-Vinyl object in `dest()`

### ISSUE THREAD

**Issue by chetanakki** [gulpjs/vinyl-fs#313]
I am using gulp ngdocs with gulp 4 and receiving the same error.
Dependency of vinyl-fs

├─┬ gulp@4.0.2
│ └── vinyl-fs@3.0.3
└─┬ gulp-ngdocs@0.3.0
└── vinyl-fs@0.3.7
Can someone help to fix this?

**Comment by phated** [comment]
That module hasn't been updated in 4 years and doesn't follow any version of the gulp plugin guidelines, so please stop using that abandoned package.
