### ISSUE TITLE
Switch to streamx

### ISSUE THREAD

**Issue by phated** [gulpjs/vinyl-fs#319]
Ref #146 

https://github.com/mafintosh/streamx

**Comment by coreyfarrell** [comment]
Switching this package to is blocked on mafintosh/streamx#14.  Same is true of `to-through`.  The patch suggested on that streamx issue allows `through2` to be replaced with `streamx.Transform` in `lib/src/`.  Changing `lib/dest/` or `lib/symlink/` results in other errors I haven't had a chance to investigate.

`lib/file-operations.js` will require use of class syntax to extend `streamx.Writable`.  It's not possible to call `streamx.Writable.call(this, options)` as streamx uses class syntax (stream v2 / v3 do not).

**Comment by jimmywarting** [comment]
Just a proposal but have you also considered using plain (async) generators/iterators?

now there is `node:stream`, `whatwg:stream` and now `streamx` and probably some other unheard of. so no wonder if ppl turns to using async iterator to handle them in the same way... without needing any extra dependencies.

**Comment by phated** [comment]
This is something I'm keeping my eye on, but I think it's too early for that for gulp. We were hoping the streamx transition would clean up some error handling in the interim.

**Comment by contra** [comment]
@jimmywarting I'm a fan of using async generators, been enjoying using them more over the last year - theoretically you can use them just fine with gulp as is (node has plenty of compat between streams and generators) it would really be more of a commitment to use them internally and update all of our docs to suggest using them. Syntactically as is it would be much more code to use generators than streams, which I think is the biggest downside. Introducing a new concept will also require a lot of education - even though generators have been out for a while they are a relatively complex subject (much as streams were initially) that would need a lot of documentation.

**Comment by jimmywarting** [comment]
> I'm a fan of using async generators

Me too, it's the bread and butter, and the only think you need to create a consumer/producer without any boilerplate code that works grate across different env.

for starters you would prefer to use `for await (let chunk of iterable)` instead of using `iterable.on('data', fn)` when ever possible...

Then there is also the possibility to use `stream.Readable.from` to turn something into a stream, think i have heard that streamx also has it...?

Here is a simple example of how u can replace eg the package concat stream with generators:

```js
async function * concatStream (otherIterable) {
  for await (let file of otherIterable) 
    yield * fs.createReadStream(file)
}

stream.Readable.from( concatStream(['./readme.md', 'licenes.md']) )
```
