### ISSUE TITLE
glob-parent vulnerability

### ISSUE THREAD

**Issue by rbruckheimer** [gulpjs/vinyl-fs#325]
A High severity vulnerability is being reported on glob-parent.  Would it be possible to bump glob-stream within vinyl-fs so it goes away?

**Comment by phated** [comment]
These will be updated in the next major version bump.

**Comment by mojavelinux** [comment]
Can you please reconsider the timing of this upgrade? vinyl-fs is a transitive dependencies of a lot of libraries, and the fact that it's pulling in a version of glob-parent with a reported vulnerability is proving nearly impossible to avoid short of ripping out everything that depends on it. Is it really a problem / breaking change to update it before publishing a major version? If so, would it be possible to push out a major version sooner? I'd be willing to help.

**Comment by phated** [comment]
It'll get done when it gets done.
