### ISSUE TITLE
breaking change in encoding

### ISSUE THREAD

**Issue by elitastic** [gulpjs/vinyl-fs#347]
I am handling with zip files. In v3.3 everything worked as expected, since v4, I have to set `encoding=false`. If I don't do that, the DLL's in the zip file are corrupt.

`vinylfs.src(glob, { encoding: false })`

Is there a breaking change in v4 regarding encoding?

// UPDATE //
I found [this commit](https://github.com/gulpjs/vinyl-fs/commit/3c67763846444a2ec47fdc67304b8b197ab0613d) marked as breaking change, but there is nothing in the v4 release notes about it?

**Comment by phated** [comment]
You're correct, encoding was added as a breaking feature, but we switched our release tool before a release was cut with it so it is missing from the changelog. We'll try to remember this when updating gulp docs for v5

**Comment by aikebah** [comment]
@phated This issue got me trialling and erroring in my project for a while before uncovering this closed issue... would appreciate a retro-active manual update of the changelog to clearly indicate this breaking change in v4.0
