### ISSUE TITLE
Incompatibility with node 22: [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.

### ISSUE THREAD

**Issue by lennybacon** [gulpjs/vinyl-fs#353]
### What were you expecting to happen?
When I run gulp I don't expect errors in the output

### What actually happened?
The error is in the output
```
(node:22952) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
    at cloneStats (REDACTED_PATH\node_modules\clone-stats\index.js:6:21)
    at File.clone (REDACTED_PATH\node_modules\vinyl-fs\node_modules\vinyl\index.js:135:23)
...
```

### Terminal output / screenshots

```sh
$ npm ls clone-stats
REDACTED_PROJECT@ REDACTED_PATH
+-- gulp-concat@2.6.1
| `-- vinyl@2.2.1
|   `-- clone-stats@1.0.0
`-- vinyl-fs@4.0.0
  +-- vinyl-sourcemap@2.0.0
  | +-- vinyl-contents@2.0.0
  | | `-- vinyl@3.0.0
  | |   `-- clone-stats@1.0.0 deduped
  | `-- vinyl@3.0.0
  |   `-- clone-stats@1.0.0 deduped
  `-- vinyl@3.0.0
    `-- clone-stats@1.0.0 deduped
```

### Please provide the following information:
OS: Windows 10
node: v22.2.0
npm: 10.7.0
gulp CLI version: 3.0.0
gulp Local version: 5.0.0

### Additional information

> Calling fs.Stats class directly with Stats() or new Stats() is deprecated due to being internals, not intended for public use.
https://nodejs.org/api/deprecations.html#DEP0180

Looks to me as if the project needs to get rid of the dependency `clone-stats`.

Of course someone could argue that [clone-stats](https://github.com/hughsk/clone-stats) should fix this, but beside the fact that the last commit is now 8 years ago, I do not see how the use of internal stuff could be fixed.

**Comment by phated** [comment]
The current version of vinyl-fs supports node 10+, so we don't make changes for bleeding edge node versions. You can add the command line flag to silence deprecation warnings.

We'll likely be switching to using `structuredClone` in the next major when we drop support of older node versions.
