### ISSUE TITLE
Preserving symlink information?

### ISSUE THREAD

**Issue by matthewwithanm** [gulpjs/vinyl-fs#38]
I recently ran into an issue using gulp-tar (sindresorhus/gulp-tar#9) where the built tar file contained actual files in place of symlinks in the source stream. I now see that the same behavior can be observed with this:

``` javascript
var fs = require('vinyl-fs');
fs.src('path/to/symlink').pipe(fs.dest('whatever'));
```

Browsing through the source, it looks like the vinyl file object doesn't expose the fact that the underlying file is a symlink so plugins can't really differentiate. (The [`file.stat` object](https://github.com/wearefractal/vinyl/blob/f12b9443138c944d0418d3513164883f6c2ee2a4/index.js#L24) includes info about the linked file a la [fs.stat](http://nodejs.org/api/fs.html#fs_fs_stat_path_callback) instead of the link a la [fs.lstat](http://nodejs.org/api/fs.html#fs_fs_lstat_path_callback).)

It would be great if vinyl supported symlinks so things like copying and tarring them were possible.

**Comment by averissimo** [comment]
@matthewwithanm did you ever got this working with `gulp-tar` ?

**Comment by matthewwithanm** [comment]
Sorry, I can't even remember 😞
