### ISSUE TITLE
Ability to create symlinks with vfs.symlink method

### ISSUE THREAD

**Issue by ben-eb** [gulpjs/vinyl-fs#42]
This is a continuation of some discussion in gulp-symlink, see: https://github.com/ben-eb/gulp-symlink/issues/19, https://github.com/ben-eb/gulp-symlink/issues/23#issuecomment-62816263

As previously stated, the current way we are handling symlinks using a transform stream, as we would use for manipulating a file's _contents_, isn't ideal. As symlinks are part of the file system it would make sense to provide this support in `vinyl-fs`, and by extension, `gulp`.

Ideally, this allows us to:
- Create symlinks with absolute or relative paths, depending on the user's preference.
- Utilise transforms already in the pipe, such as [gulp-rename](https://github.com/hparra/gulp-rename) to both rename and create the new symlink.

I think an API such as this would be good:

``` js
gulp.task('symlink', function() {
    return gulp.src('path/to/file')
        .pipe(gulp.dest('dist', {
            symlink: 'relative' // or 'absolute'
        }));
});
```

**Comment by OZZlE** [comment]
seems like with the current solution you cannot control where the symlink leads to "`cwd`, `base`, and `path` will be overwritten to match the folder"

The structure I have depends on the source file having a complete different folder structure than where the symlink should be placed inside. When I simply replaced gulp.dest() with vfs.symlink() it creates the symlink in the correct place but it leads to a non existing place.
