### ISSUE TITLE
Overwriting on a per-file basis?

### ISSUE THREAD

**Issue by troch** [gulpjs/vinyl-fs#68]
I have been working on a peculiar case: a client has developers working on different editors, and no-one bothered setting their editors / IDEs for tabs and spaces. That client also doesn't really care about style guides and as a result they introduced jsbeautify in their building process: source files are overwritten with their prettified contents. This is of course not editor friendly (causes files to be reloaded, or editors to prompt for reloads) but this is how that client does it.

The build process has been recently converted to Gulp (using Gulp 4), and to try to make the process more editor-friendly, I introduced a piece of pipeline which prettifies file contents, compare the prettified version with its original and only copy if different.

The issue I have is that I bypass gulp.dest() and use fs.writeFile() instead inside that piece of pipeline. I would prefer if I had a piece of pipeline which would prettify and set an `overwrite` flag to true if different, and then pass it to gulp.dest().

[https://github.com/wearefractal/vinyl-fs/blob/master/lib/prepareWrite.js#L15](https://github.com/wearefractal/vinyl-fs/blob/master/lib/prepareWrite.js#L15) could become:

    var overwrite = (file.overwrite !== undefined ? file.overwrite : options.overwrite);
    options.flag = (overwrite ? 'w' : 'wx');

Should I go ahead with a pull request?

**Comment by contra** [comment]
Not 100% sure on this one. Early in the AM let me chew on it for a bit.

@phated @sindresorhus ?

**Comment by phated** [comment]
Seems strange to have a file determine the flag behavior, especially because you would need some custom plugin to attach the overwrite property.  Can't this be achieved through use of gulp-if or gulp-filter?

**Comment by contra** [comment]
maybe all of the options on dest should be either value or function just to normalize it, then you can do whatever you want in your function

ie

```js
gulp.dest(folder, {overwrite: function(file){ }}
```
