### ISSUE TITLE
fs.src failing

### ISSUE THREAD

**Issue by kingmotley** [gulpjs/vinyl-fs#93]
Trying to write code to emit vinyl files for every file on my C: drive, and no matter the options I set, it fails silently or partially emits files and throws an error.  The code I have is as follows:

```javascript
	var fs = require('vinyl-fs');
	var debug = require('gulp-debug');
	fs.src('C:/**/*').pipe(debug());
```
returns:
```
S:\Users\RMcKee>gulp check
[22:54:58] Using gulpfile ~\gulpfile.js
[22:54:58] Starting 'check'...
[22:54:58] Finished 'check' after 286 ms
[22:54:58] gulp-debug: 0 items
```

It seems as if the globbing engine is firstly having a problem recognizing 'C:/' as a drive?
Changing the code to the following also fails:
```javascript
	var fs = require('vinyl-fs');
	var debug = require('gulp-debug');
	fs.src('./**/*').pipe(debug());
```
with:
```
S:\Users\RMcKee>gulp check
[23:02:18] Using gulpfile ~\gulpfile.js
[23:02:18] Starting 'check'...
[23:02:19] Finished 'check' after 320 ms
[23:02:19] gulp-debug: AppData
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, scandir 'S:\Users\RMcKee\Application Data
'
    at Error (native)
```

Changing the code to:
```javascript
	var fs = require('vinyl-fs');
	var debug = require('gulp-debug');
	fs.src('./**/*',{strict:false}).pipe(debug());
```
this should have NO effect as node-glob says all options are false by default, but it sure enough does have an effect, and after returning a ton of 'EPERM' errors, it dies again, ending with:

```
[23:05:30] gulp-debug: DevelopmentStorageDb22_log.ldf
[23:05:30] gulp-debug: Documents
[23:05:30] gulp-debug: Downloads
[23:05:30] gulp-debug: Favorites
[23:05:30] gulp-debug: fontconfig
[23:05:30] gulp-debug: gulpfile.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, open 'S:\Users\RMcKee\NTUSER.DAT'
    at Error (native)
```

**Comment by kingmotley** [comment]
Adding options {strict: false, read: false, buffer: false, nodir: true, follow: true } returns with no error, but not all the files were found.

**Comment by contra** [comment]
This is a problem with the glob library that vinyl-fs uses, not with vinyl-fs. AFAIK this has been fixed in the glob library, so we need to update

**Comment by phated** [comment]
I believe vinyl-fs master branch is using a version of glob that should have this fixed.  Can you please test with the master branch?  Thanks

**Comment by phated** [comment]
@kingmotley can you test with the master branch?  If not, I am going to assume this is fixed and close.

**Comment by kingmotley** [comment]
```javascript
    var fs = require('vinyl-fs');
    var debug = require('gulp-debug');
    fs.src('C:/**/*').pipe(debug());
```

Still doesn't work using 2.3.0

**Comment by phated** [comment]
@kingmotley you have to end on a Writeable stream, so you have to can use `vfs.dest()` (where we handle that for you), some other Writeable stream, or you can sink the stream with a module like [exuent](https://www.npmjs.com/package/exuent) as we do internally in gulp (the reason you need to return your streams).
