### ISSUE TITLE
Allow to set file stats on dest()

### ISSUE THREAD

**Issue by piranna** [gulpjs/vinyl-fs#96]
vinyl headers has support for the file stats, but `dest()` is not preserving them. opt field could accept a `stat` field and use it, I'm mostly interested on `mtime` since [download](https://github.com/kevva/download/issues/78) can't be able to preserve it, and source code tarballs fail. This can be done with the [fs.utimes()](https://nodejs.org/api/fs.html#fs_fs_utimes_path_atime_mtime_callback) function.

**Comment by contra** [comment]
Can you clarify a bit more? FYI you can do this in a plugin prior to dest - just modify file.stats

**Comment by piranna** [comment]
Thanks for the advice about the plugin ;-) What I'm asking about is that at https://github.com/contra/vinyl-fs/blob/5b056f66c476ff32687c172d5fe79eaf47b2e80e/lib/dest/writeContents/writeBuffer.js#L6-L11 and https://github.com/contra/vinyl-fs/blob/5b056f66c476ff32687c172d5fe79eaf47b2e80e/lib/dest/writeContents/writeStream.js#L7-L12 file is created with current `mtime` instead of the one defined on `file.stats`. `fs.writeFile()` and `fs.createWriteStream()` don't allow to set the stats or the time on their arguments, but this can be set with the `fs.utimes()` function, just call it after the file is created.

**Comment by contra** [comment]
@piranna Interesting... could you explain your use case a bit more? You might want to try using symlinks instead of having gulp copy the files over - use gulp.symlink instead of gulp.dest

**Comment by phated** [comment]
@contra the referenced `download` issue has more reasoning why they need the `mtime` from stats.  It seems that some files can't be unzipped if their created time is different than the original tar

**Comment by piranna** [comment]
yes, @phated is (almost) true, some times source code tarballs can't be compiled if their time is different of the original ones since `make` think they have been changed, that's why it's needed to preserve the original time. vynil headers use already the current time by default on the `stat` entry, so it's ok to set them always after the files are created.

**Comment by piranna** [comment]
I've created a [pull-request](https://github.com/gulpjs/vinyl-fs/pull/110) to fix this.

**Comment by phated** [comment]
Published this change as 2.2.0

**Comment by piranna** [comment]
Thank you :-)
